Fix exception on ARM32 with VS2022 when Print() is invoked
ncroxon/gnu-efi pull request #22
Opened 2024-05-13 15:44 UTC by pbatard

On ARM32 only, it appears that whenever Visual Studio inlines the `FloatToString()` call (which it does for Release builds), the resulting executable produces an "Undefined OpCode Exception" on `Print()` invocation, regardless of whether there is an actual float to string conversion occurring there.

To work around this, add an explicit clause to prevent Visual Studio inlining.

2024-05-13 16:39 UTC, gmbr3 requested changes
Can we create a EFI_NOINLINE macro in eficompiler.h instead so to ensure that this applied to gcc aswell even if it's not affected by the bug?

2024-05-13 17:44 UTC, pbatard commented
Sure, I should be able to work something out.

My guess however is that we have something specific to the Visual Studio code generation (e.g. alignment issue due to structs that are packed differently than with gcc), and that it's unlikely to affect other platforms. Because of time constraints, I will also state that I've stopped investigating after I found that `FloatToString()` was inlined by Visual Studio in the assembly and that de-inlining it removed the issue. But I only tested very basic applications, so it's very possible we may see similar issues on other function calls besides `Print()`.

Anyway, if we agree that we want to disable the inlining for all compilers, and not just Visual Studio, please wait for an update of this PR.

2024-05-14 07:54 UTC, gmbr3 commented
> But I only tested very basic applications, so it's very possible we may see similar issues on other function calls besides `Print()`.
> 

If we see more cases of this, only on VS, then we can decide and make further investigation regarding alignment of structs etc. The NOINLINE macro should probably be created even if we found that as it's useful for downstreams aswell.

2024-05-14 12:01 UTC, pbatard commented
Updated as requested. I also took this opportunity to clean-up `eficompiler.h` as using `#if not MSVC assume GNU` wasn't ideal compared to explicitly defining the macros for the compilers they apply.

2024-05-14 12:57 UTC, pbatard commented
Stealth update to fix a `EFI_NORETURN` that should have said `EFI_NOINLINE`

2024-05-14 20:18 UTC, ncroxon approved these changes

2024-05-14 20:19 UTC, ncroxon approved these changes

2024-05-14 20:20 UTC, merged

2024-05-15 06:28 UTC, Liai5555 reviewed
b6614502510713e348eb9675b7a89b2b7083e242

2024-05-15 11:04 UTC, ncroxon commented
@Liai5555, did you mean to add a comment?

> b6614502510713e348eb9675b7a89b2b7083e242